### ISSUE TITLE
Error 400

### ISSUE THREAD

**Issue by jdwaymire** [usnistgov/docker-control-center#1]
Deployed using command with no docker-compose file, created user/pass, when attempting to goto the ui I am presented with an error 400.  Log file below:

[06/Jun/2019 20:17:31] [django.request] WARNING Bad Request: /
[06/Jun/2019 20:17:31] [django.request] WARNING Bad Request: /favicon.ico

Any insight would be helpful.

**Comment by rptmat57** [comment]
couple of questions:

- which OS are you using?
- which url are you using to go to the UI? localhost:8000?

you can try opening `settings.py` in your configuration folder and adding `DEBUG=True`, then restart the docker container and you should see more information about the error

my guess is that you are using an IP or URL different from "localhost" to access it.

if that is the case, either:

- use localhost 
- add `ALLOWED_HOSTS = ["*"]` in `settings.py`
- add your IP to the list, for example `ALLOWED_HOSTS = ["localhost", "192.168.1.10"]` in `settings.py`

**Comment by jdwaymire** [comment]
Adding ALLOWED_HOSTS = ["localhost", "*IP*"] fixed the issue.  Thank you very much for responding.
